(TeX-add-style-hook
 "mdframed"
 (lambda ()
   (TeX-run-style-hooks
    "md-frame-0"
    "md-frame-1"
    "md-frame-2"
    "md-frame-3"
    "kvoptions"
    "xparse"
    "etoolbox"
    "zref-abspage"
    "needspace"
    "color"
    "xcolor")
   (TeX-add-symbols
    "mdf"
    "mdversion"
    "mdframedpackagename"
    "mdfmaindate"
    "mdfrevision"
    "makelabel"
    "thempfn"
    "width"
    "height"
    "iterate")
   (LaTeX-add-environments
    '("mdframed" LaTeX-env-args ["argument"] 0))
   (LaTeX-add-counters
    "mdfcountframes")
   (LaTeX-add-lengths
    "mdf"
    "csname"
    "mdfsplitboxwidth"
    "mdfsplitboxtotalwidth"
    "mdfsplitboxheight"
    "mdfsplitboxdepth"
    "mdfsplitboxtotalheight"
    "mdfframetitleboxwidth"
    "mdfframetitleboxtotalwidth"
    "mdfframetitleboxheight"
    "mdfframetitleboxdepth"
    "mdfframetitleboxtotalheight"
    "mdffootnoteboxwidth"
    "mdffootnoteboxtotalwidth"
    "mdffootnoteboxheight"
    "mdffootnoteboxdepth"
    "mdffootnoteboxtotalheight"
    "mdftotallinewidth"
    "mdfboundingboxwidth"
    "mdfboundingboxtotalwidth"
    "mdfboundingboxheight"
    "mdfboundingboxdepth"
    "mdfboundingboxtotalheight"
    "mdfsubtitleheight"
    "mdfsubsubtitleheight")
   (LaTeX-add-saveboxes
    "mdf"))
 :latex)

